# Generated by Django 5.1.2 on 2024-10-16 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50, verbose_name='Регион')),
                ('description', models.TextField()),
                ('year', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(max_length=50)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now=True)),
                ('gearbox', models.CharField(max_length=50, verbose_name='Коробка')),
                ('engine_power', models.CharField(max_length=100, verbose_name='Двигатель')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег (км)')),
                ('engine_type', models.CharField(choices=[('electric', 'Электро')], max_length=50, verbose_name='Тип двигателя')),
                ('status', models.CharField(choices=[('new', 'New'), ('used', 'Used')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_image', models.ImageField(upload_to='car_photos/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='car.car')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('black', 'Черный'), ('white', 'Белый'), ('red', 'Красный'), ('blue', 'Синий'), ('green', 'Зеленый'), ('gray', 'Серый')], default='black', max_length=10)),
                ('car_marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.marka')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='car.marka'),
        ),
    ]
